apiVersion: v1
kind: Pod
metadata: 
  labels:
    run: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.podname }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - image: {{ .Values.nginx_image.repository }}:{{ .Values.nginx_image.version }}
    name: nginx
    resources:
      limits:
        cpu: {{ .Values.resource.limits.cpu }}
        memory: {{ .Values.resource.limits.memory }}
